### ISSUE TITLE
Where's the code?

### ISSUE THREAD

**Issue by H-Park** [YeWR/EfficientZero#1]
![5vtkv3.jpg](https://user-images.githubusercontent.com/4796910/143775520-9757aa67-9801-4209-a33a-a056e9d26841.jpg)

**Comment by neverix** [comment]
On the authors' computers probably

**Comment by H-Park** [comment]
![5vtkv3.jpg](https://user-images.githubusercontent.com/4796910/143775515-c20cd692-8b58-4e2e-9271-954f0f44cd3c.jpg)

**Comment by JulianKu** [comment]
Released now
