### ISSUE TITLE
what does reward_hidden_c mean in mcts.py?

### ISSUE THREAD

**Issue by sekv** [YeWR/EfficientZero#11]
Hi, In mcts.py code line 35-36, what does reward_hidden_c and reward_hidden_h mean? ( what is c and h short for?) why reward_hidden_c_pool = [reward_hidden_roots[0]] and reward_hidden_h_pool = [reward_hidden_roots[1]].  I find it difficult to understand the code, could you give some comments. Many thanks!
<img width="804" alt="截屏2022-01-20 下午9 25 09" src="https://user-images.githubusercontent.com/26269002/150348329-459a7e44-4ce6-4b6c-b801-3398e67fd996.png">

**Comment by YeWR** [comment]
We use nn.LSTM to handle the prediction of the value prefix. And the input/output of nn.LSTM contains the final hidden states and the final cell states.

![image](https://user-images.githubusercontent.com/38777533/151359561-bcb950b1-6300-4a5e-a83c-4e87c2c20b37.png)

For detailed usage, please refer to https://pytorch.org/docs/1.9.1/generated/torch.nn.LSTM.html.
But they are tuple. The `xxx_pool`s in mcts.py are simple structured databases for saving the corresponding data. For better indexing, the tuple is split into two arrays, namely `c_pool` and `h_pool`.
Hope this can help you:)

**Comment by sekv** [comment]
Got it! Thank you for your detailed reply:)
