### ISSUE TITLE
procgen

### ISSUE THREAD

**Issue by hlsafin** [YeWR/EfficientZero#25]
Can this be tried out on procgen environment?

**Comment by reinforcementwonder** [comment]
You can modify the environment and someone has already done this [before](https://arxiv.org/abs/2111.01587).

**Comment by PeppaCat** [comment]
You can modify the environment and someone has already done this [before](https://arxiv.org/abs/2111.01587).

**Comment by hlsafin** [comment]
Thank you, also Am I able to run this only on a single 3080? What do you advise I should do?

**Comment by hlsafin** [comment]
Yeah, they didn't release their code. I'm just trying to assess this EfficenetZero generality, because atari env can be quite deterministic.
