### ISSUE TITLE
Removing Baselines dependency

### ISSUE THREAD

**Issue by araffin** [YeWR/EfficientZero#3]
Hello,
it would be nice to remove baselines dependency (as it requires tensorflow, whereas the rest of the codebase is written with pytorch).
As apparently it is used for atari wrappers only, there are few options:
- use the ones that are now in Gym (but I'm not sure they are exactly the same)
- use the ones from Stable-Baselines3 (also depends on pytorch, so less dependencies)
- copy them into the repo

**Comment by YeWR** [comment]
Really thank you for your suggestions! We have removed the baselines dependency via "copying them into the repo". 
All the best.
