### ISSUE TITLE
BreakoutNoFrameskip-v4 is not registered?

### ISSUE THREAD

**Issue by SpotEvictionPrediction** [YeWR/EfficientZero#7]
Got an error with the example train.sh showing _'gym.error.UnregisteredEnv: No registered env with id: BreakoutNoFrameskip-v4'_

**Comment by YeWR** [comment]
It seems an issue with your Gym package installation. Could you try to reinstall the gym and atari-py package?

**Comment by SpotEvictionPrediction** [comment]
Thanks, fixed.
